name: "Build Node App"
description: "Installs dependencies, builds app, and prepares artifacts"
inputs:
  node-version:
    description: "Node.js version"
    required: false
    default: "18"
outputs:
  build-path:
    description: "Path to build output"
    value: ${{ steps.set-output.outputs.path }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build app
      run: npm run build
      shell: bash

    - name: Set build output
      id: set-output
      run: echo "path=dist" >> $GITHUB_OUTPUT
      shell: bash
