name: Node.js CI Template

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        description: 'Node.js version'
        required: false
        default: '18'
      environment:
        description: 'Deployment environment'
        required: false
        default: 'staging'
        type: string

jobs:
  test-and-build:
    name: Test and Build
    uses: ./.github/workflows/build-and-cache.yml
    with:
      node-version: ${{ inputs.node-version }}
      environment: ${{ inputs.environment }}

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test-and-build
    if: ${{ needs.test-and-build.outputs.build-completed == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Dependency review
        uses: actions/dependency-review-action@v3

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: [test-and-build, security-scan]
    if: always()
    
    steps:
      - name: Notify build status
        run: |
          echo "Build completed with status: ${{ needs.test-and-build.outputs.build-completed }}"
          echo "Security scan completed: ${{ needs.security-scan.result }}"